-- ============================================
-- 星域臻旅 - 公司/员工档案 + 补 driver/butler 字段
-- ============================================

-- 1. company_profile（公司基本信息）
CREATE TABLE IF NOT EXISTS public.company_profile (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id text,
  company_name text,
  company_web_url text,
  company_code text,
  email text,
  whatsapp text,
  wechat text,
  wallet_balance text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. company_private_data（公司私密资料：SSM 注册 + 银行；结构沿用 butler_private_data 并追加字段）
CREATE TABLE IF NOT EXISTS public.company_private_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  ic_full_name text,
  ic_gender text,
  date_of_birth date,
  place_of_birth text,
  nationality text,
  ic_number text,
  ic_address text,
  ic_postcode text,
  ic_city text,
  ic_state text,
  ic_front_url text,
  ic_back_url text,
  company_name text,
  company_web_url text,
  bank_brand text,
  bank_holder_name text,
  bank_account text,
  ssm_bis_info_url text,
  ssm_cert_url text,
  ssm_borang_a_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. staff_profile（员工基本信息，同 butler_profile 结构）
CREATE TABLE IF NOT EXISTS public.staff_profile (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id text,
  username text,
  email text,
  whatsapp text,
  wechat text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. staff_private_data（员工私密资料，同 butler_private_data 结构）
CREATE TABLE IF NOT EXISTS public.staff_private_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  ic_full_name text,
  ic_gender text,
  date_of_birth date,
  place_of_birth text,
  nationality text,
  ic_number text,
  ic_address text,
  ic_postcode text,
  ic_city text,
  ic_state text,
  ic_front_url text,
  ic_back_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 5. driver_profile 补 company_id（wallet_balance 已存在，跳过）
ALTER TABLE public.driver_profile ADD COLUMN IF NOT EXISTS company_id text;

-- 6. butler_profile 补 company_id / wallet_balance
ALTER TABLE public.butler_profile ADD COLUMN IF NOT EXISTS company_id text;
ALTER TABLE public.butler_profile ADD COLUMN IF NOT EXISTS wallet_balance text;

-- 7. driver_private_data 补银行 + uuid（uuid 已存在，跳过）
ALTER TABLE public.driver_private_data ADD COLUMN IF NOT EXISTS bank_brand text;
ALTER TABLE public.driver_private_data ADD COLUMN IF NOT EXISTS bank_holder_name text;
ALTER TABLE public.driver_private_data ADD COLUMN IF NOT EXISTS bank_account text;
ALTER TABLE public.driver_private_data ADD COLUMN IF NOT EXISTS uuid uuid DEFAULT gen_random_uuid();

-- 8. butler_private_data 补银行 + uuid
ALTER TABLE public.butler_private_data ADD COLUMN IF NOT EXISTS bank_brand text;
ALTER TABLE public.butler_private_data ADD COLUMN IF NOT EXISTS bank_holder_name text;
ALTER TABLE public.butler_private_data ADD COLUMN IF NOT EXISTS bank_account text;
ALTER TABLE public.butler_private_data ADD COLUMN IF NOT EXISTS uuid uuid DEFAULT gen_random_uuid();

-- 9. 新表启用 RLS（敏感数据默认锁定，不做 anon 公开策略）
ALTER TABLE public.company_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_private_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_private_data ENABLE ROW LEVEL SECURITY;
