-- ============================================
-- 星域臻旅 - 订单金额表 order_amounts
-- ============================================

CREATE TABLE IF NOT EXISTS public.order_amounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text,
  order_no text,
  base_price numeric(12,2),
  car_upgrade_fee numeric(12,2),
  car_reduce_fee numeric(12,2),
  discount numeric(12,2),
  final_amount numeric(12,2),
  status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS：客户端 anon 可读写
ALTER TABLE public.order_amounts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_insert_order_amounts" ON public.order_amounts;
CREATE POLICY "anon_insert_order_amounts" ON public.order_amounts FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "anon_select_order_amounts" ON public.order_amounts;
CREATE POLICY "anon_select_order_amounts" ON public.order_amounts FOR SELECT TO anon USING (true);
